### ISSUE TITLE
关于demo中retrofit网络请求的问题

### ISSUE THREAD

**Issue by Wagner0630** [zjutkz/AndroidArchitectureDemo#1]
当我点击get按钮的时候，请求网络显示数据，当我再次点击get按钮的时候为什么dialog一直在显示，而网络请求有没有在更新数据呢？按理来说它应该返回结果然后dialog消失，大神，求解。。。。

**Comment by zjutkz** [comment]
@want-gone 第二次rxjava对应的没有走到onNext方法中(但是调用了onStart方法)。

**Comment by Wagner0630** [comment]
@zjutkz 第二次为什么没有走到onNext方法？怎样才能再次走到onNext方法？

**Comment by zjutkz** [comment]
@want-gone 应该是rxjava的机制问题，对于rxjava我的了解不是非常多 不好意思

**Comment by Wagner0630** [comment]
@zjutkz 好的，谢谢，感谢指教~
